name: AI Commit Summary

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get commit messages
        run: |
          git fetch origin main
          git log origin/main..HEAD --pretty=format:"- %s" > commits.txt

      - name: Generate AI summary
        id: ai
        uses: openai/openai-github-actions@v1
        with:
          model: gpt-4o-mini
          prompt: |
            以下のコミットメッセージを読み取り、Pull Request の「変更内容」をレビューアー向けに簡潔に要約してください。
            ```
            $(cat commits.txt)
            ```
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const summary = `${{ steps.ai.outputs.response }}`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🤖 **AI要約**:\n\n${summary}`
            })
